name: Build CrossComple .net core/.net framework Windows

on: [push]

jobs:
  build:
    name: Test Windows .net Framework Only
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: NuGet/setup-nuget@v2
    - uses: microsoft/setup-msbuild@v2
      with:
        dotnet-version: 4.7.2
    
    - name: Restore
      run: dotnet restore -p:TargetFramework=net472
    - name: Build
      run: dotnet build -f net472 --no-restore -t:rebuild -property:Configuration=Release
    - name: Test
      run: dotnet test --configuration Release --no-build --no-restore
