name: .net framework Windows

on: [push]

jobs:
  build:
    name: Test Windows .net Framework Only
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Build
      run: dotnet build DotNetDBF.sln --configuration Release
    - name: Test
      uses: josepho0918/vstest-action@0e887de8dcfab5ce3eecaf4ad6320bb9b3ecf633
      with:
        testAssembly: DotNetDBF.Test.exe
        searchFolder: .\DotNetDBF.Test\bin\Release\net48\
        runInParallel: true
        platform: x64
    - name: Publish
      run:
        dotnet nuget push '${{ github.workspace }}\publish\*.nupkg' --source https://nuget.pkg.github.com/ekonbenefits/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
