name: Build CrossComple .net core/.net framework Windows

on: [push]

jobs:
  build:
    name: Test Windows .net Framework Only
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        dotnet-version: 4.7.2
    
    # - name: Restore Packages
    #   run: nuget restore DotNetDBF.sln
    # - name: Build solution
    #   run: msbuild DotNetDBF.sln -t:rebuild -property:Configuration=Release
    # - name: Run vstests
    #   uses: microsoft/vstest-action@v1.0.0
    #   with:
    #     testAssembly: Tests.dll
    #     searchFolder: .\Tests\bin\Release\*\
    #     runInParallel: true
    #     platform: x64
    - name: Restore
      run: dotnet restore -p:TargetFramework=net472
    - name: Build
      run: dotnet build -f net472 -t:rebuild -property:Configuration=Release
    - name: Test
      run: dotnet test --configuration Release --no-build --no-restore
